name: CreativeVega
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343434'
    - '#5895c3'
    - '#e6e6e6'
    - '#ffffff'
    - '#ea4e49'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
